version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/webview_panels"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"
