// Probe targets. `jaffle` is prepared by prep-jaffle.sh; `finance` is a copy of finance_general without target/ or
// logs/ (see run.sh), so the language server never writes into the original project.
// Adds `col` to a model's output without knowing its last line; Jinja blocks inside the parentheses render as before.
const dotAppend = (col) => (sql) => `select probe_wrapped.*, 1 as ${col} from (\n${sql}\n) as probe_wrapped\n`;

export const configs = {
  jaffle: {
    root: process.env.JAFFLE_ROOT ?? "/tmp/lsp-jaffle",
    lspArgs: ["--static-analysis", "strict"],
    uniqueId: "model.jaffle_shop.orders",
    column: "amount",
    otherModelName: "customers",
    tag: undefined,
    seedSelector: "raw_orders",
    exposureSelector: "exposure:weekly_report",
    cteName: "order_payments",
    symbolQuery: "orders",
    showInline: "select * from {{ ref('orders') }}",
    columnProbes: [
      ["+column:model.jaffle_shop.customers.customer_id+"],
      ["@model.jaffle_shop.customers", "+column:model.jaffle_shop.customers.customer_id+"],
      ["+column:model.jaffle_shop.stg_orders.order_id+"],
      ["+column:model.jaffle_shop.orders.order_id+"],
      ["@model.jaffle_shop.orders", "+column:model.jaffle_shop.orders.amount+"],
      ["@model.jaffle_shop.orders", "2+column:model.jaffle_shop.orders.amount"],
      ["+column:model.jaffle_shop.payments_dollars.amount_dollars+"],
      ["+column:source.jaffle_shop.raw.raw_orders.id+"],
    ],
    files: {
      model: "models/orders.sql",
      cteModel: "models/orders.sql",
      lensAlso: ["models/schema.yml", "models/sources.yml", "models/src_orders.sql"],
      openAlso: ["models/customers.sql", "models/payments_dollars.sql", "models/src_orders.sql", "models/schema.yml"],
      currentNodeAlso: ["models/staging/stg_orders.sql", "seeds/raw_orders.csv", "models/schema.yml"],
    },
    positions: {
      "ref('stg_orders')": { file: "models/orders.sql", find: "stg_orders", offset: 2, references: true },
      "macro cents_to_dollars(": { file: "models/payments_dollars.sql", find: "cents_to_dollars('amount')", offset: 3, signature: true, references: true },
      "dotted jaffle_shop.cents_to_dollars": { file: "models/payments_dollars.sql", find: "jaffle_shop.cents_to_dollars", offset: 15, signature: true },
      "source('raw','raw_orders')": { file: "models/src_orders.sql", find: "raw_orders", offset: 2 },
      "column customer_orders.first_order": { file: "models/customers.sql", find: "customer_orders.first_order", offset: 18, references: true },
      "alias total_amount": { file: "models/orders.sql", find: "total_amount", offset: 2, references: true, rename: true },
      "select *": { file: "models/orders.sql", find: "select * from final", offset: 7 },
      "yaml model name": { file: "models/schema.yml", find: "name: orders", offset: 7, references: true },
      "doc() in yaml": { file: "models/schema.yml", find: "orders_status", offset: 2 },
    },
    completions: {
      "ref('": { file: "models/orders.sql", append: "select * from {{ ref('", trigger: "'" },
      "source('": { file: "models/orders.sql", append: "select * from {{ source('", trigger: "'" },
      "source('raw', '": { file: "models/orders.sql", append: "select * from {{ source('raw', '", trigger: "'" },
      "{{ (macro)": { file: "models/orders.sql", append: "select {{ ", trigger: "{" },
      "jaffle_shop.": { file: "models/orders.sql", append: "select {{ jaffle_shop.", trigger: "." },
      "column after alias.": { file: "models/customers.sql", append: "select customer_orders.", trigger: "." },
      "select-list (no trigger)": { file: "models/orders.sql", append: "select ord" },
    },
    freshness: {
      file: "models/orders.sql",
      closedFile: "models/staging/stg_payments.sql",
      append: dotAppend("probe_fresh_col"),
      column: "probe_fresh_col",
      newModelSql: "select 1 as id\n",
    },
    diagnostics: {
      file: "models/customers.sql",
      cases: {
        "missing ref": (sql) => sql.replace("ref('stg_customers')", "ref('no_such_model')"),
        "jinja syntax": (sql) => sql.replace("{{ ref('stg_customers') }}", "{{ ref('stg_customers') }"),
        "unknown column (strict)": (sql) => sql.replace("customers.first_name,", "customers.no_such_column,"),
        "missing env_var": (sql) => `{{ env_var('FPU_PROBE_UNSET_VAR') }}\n${sql}`,
      },
    },
  },
  finance: {
    root: process.env.FINANCE_ROOT ?? "/tmp/lsp-fin/finance_general",
    profilesDir: process.env.DBT_ENGINE_PROFILES_DIR,
    lspArgs: ["--static-analysis", process.env.FINANCE_STATIC_ANALYSIS ?? "baseline"],
    loadTimeoutMs: 600000,
    samples: 5,
    uniqueId: "model.finance_general.stg__stripe__transfer_reversal",
    column: "TRANSFER_REVERSAL_NK",
    otherModelName: "stg__marqeta__declines",
    tag: "tag:source_system/stripe_grant",
    seedSelector: "resource_type:seed",
    exposureSelector: undefined,
    cteName: "unioned",
    symbolQuery: "stripe",
    showInline: "select * from {{ ref('base__stripe_grant__topup') }}",
    columnProbes: [
      ["+column:model.finance_general.stg__stripe__transfer_reversal.TRANSFER_REVERSAL_NK+"],
      ["@model.finance_general.stg__stripe__transfer_reversal", "+column:model.finance_general.stg__stripe__transfer_reversal.TRANSFER_REVERSAL_NK+"],
    ],
    files: {
      model: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql",
      cteModel: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql",
      lensAlso: ["models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.yml"],
      openAlso: ["models/13_staging/money_movement/marqeta/stg__marqeta__declines.sql", "models/12_base/money_movement/stripe_grant/base__stripe_grant__topup.sql"],
      currentNodeAlso: ["models/13_staging/money_movement/marqeta/stg__marqeta__declines.sql", "models/12_base/money_movement/stripe_grant/base__stripe_grant__topup.sql"],
    },
    positions: {
      "ref('base__stripe_grant__transfer_reversal')": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", find: "base__stripe_grant__transfer_reversal", offset: 2, references: true },
      "dotted kikoff.union_relations": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", find: "kikoff.union_relations", offset: 8, signature: true },
      "dotted temporalize.reconcile": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", find: "temporalize.reconcile", offset: 13, signature: true, references: true },
      "source('stripe_grant','topup')": { file: "models/12_base/money_movement/stripe_grant/base__stripe_grant__topup.sql", find: "source('stripe_grant', 'topup')", offset: 9 },
      "select *": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", find: "select * from final", offset: 7 },
    },
    completions: {
      "ref('": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", append: "select * from {{ ref('", trigger: "'" },
      "source('": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", append: "select * from {{ source('", trigger: "'" },
      "temporalize.": { file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql", append: "{{ temporalize.", trigger: "." },
    },
    freshness: {
      file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql",
      closedFile: "models/13_staging/money_movement/stripe/stg__stripe__topup.sql",
      append: dotAppend("probe_fresh_col"),
      column: "probe_fresh_col",
      newModelSql: "select 1 as id\n",
    },
    diagnostics: {
      file: "models/13_staging/money_movement/stripe/stg__stripe__transfer_reversal.sql",
      cases: {
        "missing ref": (sql) => sql.replace("ref('base__stripe_grant__transfer_reversal')", "ref('no_such_model')"),
        "missing env_var": (sql) => `{{ env_var('FPU_PROBE_UNSET_VAR') }}\n${sql}`,
      },
    },
  },
};
